### ISSUE TITLE
Setting up a component for the chat function

### ISSUE THREAD

**Issue by alvitoraidhy** [chingu-voyages/v36-bears-team-20#26]
**__Task Description__**
Need to create a React component for the chat function that would give the attendees and the organizers the ability to send and receive messages between each other.

**__Technical Considerations__**
TBA

**__Additional Considerations__**
TBA

**Comment by elliotwutingfeng** [comment]
![Peek 2022-01-27 23-24](https://user-images.githubusercontent.com/30223404/151389243-5a25b1f8-0a69-4ef5-b683-c0ffc36a82c6.gif)
